tikv/raft-engine

Cargo.toml, src/config.rs, src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/metrics.rs, src/pipe_log.rs
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> init raft-engine lib

Cargo.toml, src/engine.rs, src/errors.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs
=> add trait RaftEngine and WriteBatch

src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/util.rs
=> add cache stats

src/engine.rs, src/lib.rs, src/memtable.rs
=> fetch_entries_to returns count instead of size

src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/util.rs
=> improve some interfaces in trait RaftEngine

Cargo.toml, src/engine.rs, src/log_batch.rs, src/memtable.rs, src/util.rs
=> correct log batch compression

src/engine.rs, src/memtable.rs
=> use cache stats in memtable

Cargo.toml
=> downgrade compress

Cargo.toml, src/log_batch.rs
rust-rocksdb also uses lz4-sys.
=> compression: switch to lz4-sys

Cargo.toml, src/codec.rs, src/config.rs, src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, src/util.rs
=> add gc and purge

src/pipe_log.rs
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
=> fix cargo check

src/cache_evict.rs, src/engine.rs, src/lib.rs, src/pipe_log.rs
=> refactor cache notification and adjust interfaces

.github/workflows/rust.yml, README.md
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
=> Add github action badge

src/lib.rs
=> add 2 interfaces for metrics flush

src/engine.rs
=> a little adjust about rewrite logic

src/cache_evict.rs, src/engine.rs, src/lib.rs, src/pipe_log.rs
Fixed https://github.com/tikv/raft-engine/issues/31
=> Pipe log trait

src/cache_evict.rs, src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, src/purge.rs, src/util.rs
=> re-implement rewrite logic

.github/workflows/rust.yml, src/engine.rs, src/memtable.rs
=> recovery from rewrite queue correctly

Cargo.toml, src/cache_evict.rs, src/codec.rs, src/config.rs, src/engine.rs, src/errors.rs, src/lib.rs, src/metrics.rs, src/pipe_log.rs, src/purge.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
* update some dependencies
* use `thiserror` intead of `quick-error` for error handling
* make `clippy` happy
=> update some dependencies

src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs
* Avoid copy when compressing log batches;
* Calculate encoded_size during encoding a log batch;
=> improve write logic to reduce cpu usage

src/cache_evict.rs, src/engine.rs, src/lib.rs, src/memtable.rs, src/pipe_log.rs
=> rename cache stats to global stats

src/cache_evict.rs, src/engine.rs, src/lib.rs, src/memtable.rs, src/pipe_log.rs, src/purge.rs
=> change some internal functions to methods

Cargo.toml
=> remove useless dependencies

src/config.rs, src/engine.rs, src/memtable.rs
=> rewrite needs to update offset/len of an entry

src/cache_evict.rs, src/engine.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, src/util.rs
=> cache evictor needs to consider queue

src/purge.rs
=> fix a dead lock bug in purge manager

.github/workflows/rust.yml, .gitignore, Cargo.toml, examples/append_compact_purge.rs, src/cache_evict.rs, src/config.rs, src/engine.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, src/purge.rs
=> code refactor about purge and rewrite

Cargo.toml, src/engine.rs, src/lib.rs, src/log_batch.rs, src/pipe_log.rs, src/purge.rs
* only purge files that have already been rewritten
* encode empty entries correctly
=> only purge files that have already been rewritten

src/engine.rs, src/log_batch.rs, src/purge.rs
=> fix panics for recovering from cleaned raft groups

src/engine.rs
=> allow to get all raft groups

src/log_batch.rs
=> add merge and approximate_size for LogBatch

src/engine.rs, src/file_pipe_log.rs, src/log_batch.rs, src/purge.rs
=> Keep log batch items private

src/engine.rs, src/event_listener.rs, src/file_pipe_log.rs, src/lib.rs, src/purge.rs, src/util.rs, stress/src/main.rs
What's changed?
- expose interface and struct about listeners.
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
=> add written bytes to stress output

src/engine.rs, stress/src/main.rs
Add a `reuse-data` flag for stress.
=> minor improvements of stress test

benches/bench_recovery.rs
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
=> Adapt benches to new interfaces

src/log_file.rs
=> use 644 permission for data files

src/config.rs, src/engine.rs, src/util.rs, stress/src/main.rs
=> sanitize configuration on startup

.github/workflows/rust.yml, src/log_batch.rs, src/test_util.rs
=> improve test coverage of log_batch.rs

src/codec.rs, src/config.rs, src/util.rs, src/write_barrier.rs
=> improve test coverage of miscellaneous modules

.github/workflows/rust.yml, src/engine.rs, src/lib.rs, src/log_file.rs, src/memtable.rs, src/purge.rs
=> improve test coverage of memtable.rs

src/write_barrier.rs
To pass [Rudra](https://github.com/sslab-gatech/Rudra) check.
=> remove unrestricted implementation of Sync

Cargo.toml
Signed-off-by: Xinye Tao <xy.tao@outlook.com>
=> update fail to 5.0

.github/workflows/rust.yml, Cargo.toml
=> cache dependencies in CI

src/engine.rs, src/file_pipe_log/builder.rs, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe_log.rs, src/memtable.rs, src/purge.rs, tests/failpoints/test_engine.rs, tests/failpoints/test_io_error.rs
Bugs:
- Unremoved obsolete files might crash recovery
Test case:
- Rewrite queue squeeze operation might encounter new appends
- Normal write IO errors
=> fix bugs and add more test cases

src/config.rs
=> fix backward compatibility issue of recovery-mode

.github/dependabot.yml, src/consistency.rs, src/engine.rs
=> add dependabot

.github/dependabot.yml, ctl/Cargo.toml, ctl/src/main.rs, src/config.rs, stress/Cargo.toml, stress/src/main.rs
Make sure config strings of newer version can be recognized by older versions.
=> fix backward compatibility of recovery-mode

stress/src/main.rs
=> fix wrong default parameter values in stress

src/memtable.rs
=> use hashed id to locate memtable slot

src/engine.rs, src/lib.rs, src/memtable.rs
=> add `get_used_size` interface for engine

Cargo.toml, README.md, ctl/src/main.rs, src/codec.rs, src/consistency.rs, src/engine.rs, src/event_listener.rs, src/file_builder.rs, src/file_pipe_log/format.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/file_pipe_log/reader.rs, src/filter.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/metrics.rs, src/pipe_log.rs, src/purge.rs, src/test_util.rs, src/write_barrier.rs, stress/Cargo.toml, stress/src/main.rs, tests/failpoints/test_engine.rs, tests/failpoints/test_io_error.rs
Add doc comments to the codebase.
And fixed a memtable bug introduced in #182. Commented and covered.
=> more comments please

rustfmt.toml, src/engine.rs, src/file_pipe_log/pipe_builder.rs, src/test_util.rs
=> add rustfmt.toml

.github/workflows/rust.yml, Cargo.toml, README.md, src/lib.rs, src/log_batch.rs, src/memtable.rs, tests/benches/mod.rs, tests/failpoints/mod.rs
=> introduce nightly feature

src/env/default.rs, src/env/mod.rs, src/env/obfuscated.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/lib.rs, src/memtable.rs
=> remove unstable feature `btree_drain_filter`

ctl/src/lib.rs, src/engine.rs, src/env/obfuscated.rs, src/lib.rs
=> chores: fix ctl repair and export env module

.github/workflows/rust.yml, ctl/Cargo.toml, src/log_batch.rs
=> trigger GitHub action on any branch

src/engine.rs, src/memtable.rs
=> update global stats when memtable is dropped

README.md, ctl/Cargo.toml
=> chore: update package info for raft-engine-ctl

.github/workflows/rust.yml, Cargo.toml, README.md, src/config.rs, src/engine.rs, src/lib.rs, src/memtable.rs, src/metrics.rs, src/purge.rs, src/swappy_allocator.rs, src/util.rs, tests/failpoints/mod.rs, tests/failpoints/test_io_error.rs
Ref #205
An allocator that switches to file-based mmap when memory usage is above certain watermark.
Micro-benchmarks:
```
test swappy_allocator::tests::bench_allocator_fast_path     ... bench:         295 ns/iter (+/- 165)
test swappy_allocator::tests::bench_allocator_slow_path     ... bench:      92,075 ns/iter (+/- 12,995)
test swappy_allocator::tests::bench_allocator_std_global    ... bench:         252 ns/iter (+/- 41)
```
buffered write (`./target/release/stress --path /data3/re_bench --time 120 --regions 1000 --write-threads 1 --write-without-sync`):
```
master:
Throughput(QPS) = 17314.75
Latency(μs) min = 19, avg = 41.10, p50 = 31, p90 = 49, p95 = 57, p99 = 81, p99.9 = 2289, max = 5151
Fairness = 100.0%
Write Bandwidth = 181.3MiB/s
swap …
```
=> support memory swap out

ctl/Cargo.toml, ctl/src/lib.rs, stress/Cargo.toml, stress/src/main.rs
Signed-off-by: Uchiha007 <harry0349a@gmail.com>
=> Upgrade clap to stable version

.github/workflows/rust.yml, Cargo.toml, src/log_batch.rs
To include the fix for nightly build issue: https://github.com/rhaiscript/rhai/commit/87273c5421b560c68e8b8ba31913091080199d77
=> Update rhai to 1.7 and update nightly toolchain in CI

CHANGELOG.md, src/engine.rs, src/env/default.rs, src/env/mod.rs, src/env/obfuscated.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/lib.rs, tests/failpoints/test_engine.rs
=> Add metadata deletion capability to `FileSystem` trait (#229)

src/engine.rs, src/env/mod.rs, src/file_pipe_log/pipe_builder.rs
=> simplify `delete_metadata` trait method (#232)

CHANGELOG.md, Cargo.toml, README.md, ctl/Cargo.toml, stress/Cargo.toml
=> bump 0.2.1

src/memtable.rs
=> fix append recovery bug (#251)

CHANGELOG.md, Cargo.toml, README.md, ctl/Cargo.toml, stress/Cargo.toml
=> bump 0.2.2

.github/workflows/rust.yml, CHANGELOG.md, Cargo.toml, Makefile, README.md, ctl/Cargo.toml, src/file_pipe_log/format.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/reader.rs, stress/Cargo.toml
Also patched changelog for: #251
=> bump 0.3.0

Makefile
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
This pr is used to supplement extra `clean` and `ctl` settings in Makefile.
=> Supplment `clean`&`ctl` for Makefile.

src/file_pipe_log/pipe_builder.rs, src/log_batch.rs
- Sync file after truncating tail corruption.
- Fix a header decoding check.
=> fix two minor issues

src/file_pipe_log/pipe.rs, src/metrics.rs
This pr supplements the necessary metrics for monitoring the amount of recycled logs.
=> add metrics of recycled file count

CHANGELOG.md, src/config.rs
As the title shows, this pr is used to enable log recycling as default.
=> Enable log recycling by default

.github/workflows/rust.yml, OWNERS
Strengthen reviewing controlling
add approvers and reviewers from community team members, but limit the contributors to this repository.
Close #360
Ref: https://github.com/tikv/community/blob/master/teams/tikv/team.json
=> ci: add prow OWNERS file

src/engine.rs
This is a manual CP of #382
PR [#370](https://github.com/tikv/raft-engine/pull/370) fixed a panic issue caused by concurrent updates to `Memtable` followed by reads on stale indexes. However, we observed that this fix introduced performance regressions under concurrent read/write workloads.
When `fetch_entries_to` retrieves a large batch of entries from disk, write operations are blocked until the read completes, delaying `Memtable` updates and degrading throughput.
This PR optimizes `fetch_entries_to` to reduce contention and improve performance under mixed workloads.
| Branch | Status |
| --- | --- |
| [Master](https://github.com/tikv/raft-engine/commit/392f5e66f8286dc1b6d7cf69f2bc20ed72d40123) | ![image](https://github.com/user-attachments/assets/72b2e5b3-56a2-4938-aebd-15a3090b9e15) | …
=> [cp-7.5] Optimize `fetch_entries_to` function to avoid stucking `write` too long. (#382)
