src/pipe_log.rs
=> fix all test cases

Cargo.toml, src/engine.rs, src/lib.rs, src/log_batch.rs
- get rid of old version of spin, which is vulnerable
- use the same crc library as TiKV
- make it compile and test using stable rust
=> *: update dependencies

Cargo.toml
All those features are not used and can make TiKV fail to compile.
=> prometheus: remove unnecessary features

src/errors.rs, src/pipe_log.rs
This PR trys to simplify `pipe_log.rs` and make it more clear. So that we can introduce other improvements easilier.
=> make pipe_log.rs more simple and clear

.github/workflows/rust.yml, src/pipe_log.rs
`fallocate` works only under linux, and many of our developers are not using linux.
Currently `fallocate` is always on, which prevent raft-engine and crates depends on it from building, eg. [tikv#8570](https://github.com/tikv/tikv/issues/8570).
This pr and `cfg`s to enable fallocate only on linux.
This should close #34.
=> Prevent using fallocate on platforms other than linux

src/engine.rs, src/purge.rs
It's possible for a region:
1. rewrite some entries and kvs into the rewrite queue
2. then the region has been removed from the engine
3. The log contains the `Command::Clean` for the region has been purged.
4. The regine restarts, the removed region appears again because there are some entires in the rewrite queue.
This PR resolves it. The `Command::Clean` will be written into the rewrite queue before the append queue has been purged.
=> clean regions from rewrite queue

src/cache_evict.rs, src/engine.rs, src/lib.rs, src/memtable.rs, src/pipe_log.rs, src/purge.rs
Previously the rewrite queue's size can only grow but not decrease even if content in it are compacted.
This PR GCs the rewrite queue if necessary, so that it's size won't grow too large.
=> squeeze the rewrite queue if necessary

src/pipe_log.rs
Without the patch `truncate_log_file` will do nothing for switching active log file. This PR fixes it.
=> truncate and sync active log correctly

src/errors.rs, src/file_pipe_log.rs, src/lib.rs
Previously we use [u8] to define version. It's hard to make sure everything is right (see [raft-engine#79](https://github.com/tikv/raft-engine/pull/79)).
For now RaftEngine is not GA, it's better change the version format to u64.
**IMPORTANT: Make sure that there MUST BE NO user using RaftEngine.**
**This patch is not compatibility with the previous log file foramt!!!**
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
=> Change `version` format to u64

.github/workflows/rust.yml, Cargo.toml, examples/append_compact_purge.rs, src/codec.rs, src/config.rs, src/engine.rs, src/errors.rs, src/event_listener.rs, src/file_pipe_log.rs, src/lib.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, src/purge.rs, src/util.rs
~1. Remove generic type in `MemTable`~
2. Update name and placement for function and constant
3. Remove redundant functions
4. Reduce uses of `unwrap()` or `expect(..)` in production code
5. Simplify generic parameters from `E: Message`, `W: EntryExt<E>` to `M: MessageExt`
~6. Directly store `protobuf::Message` in memtable~
=> Improve codebase readability

Cargo.toml, benches/bench_recovery.rs, src/file_pipe_log.rs, src/util.rs
Add recovery benchmarking.
use `cargo bench --features=failpoints` to run `bench_recovery`.
To get the complete output, you may want to run:
```bash
cargo bench --bench bench_recovery --features="failpoints" -- --verbose --nocapture
```
=> Add bench case for recovery.

benches/bench_recovery.rs
With `nightly-2021-07-28-x86_64-unknown-linux-gnu(rustc 1.56.0-nightly,
2faabf579)` on Centos, `bench_recovery` cannot compile. Add this line
will fix the problem.
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
=> Fix build with older version on some platform.

Cargo.toml, benches/bench_recovery.rs, examples/append_compact_purge.rs, src/engine.rs, src/errors.rs, src/file_pipe_log.rs, src/file_system.rs, src/lib.rs, src/log_batch.rs, src/log_file.rs, src/pipe_log.rs, src/purge.rs, src/reader.rs, stress/src/main.rs
=> Introduce file system and implement streaming encoding

.github/workflows/rust.yml, benches/bench_recovery.rs, examples/append_compact_purge.rs, src/engine.rs, src/lib.rs, src/log_batch.rs, src/purge.rs, src/util.rs, stress/src/main.rs
1. Append compressed entries to log batch buffer instead of replacing the buffer.
2. Avoid allocate twice when creating `protobuf::Message` from decompressed slice
3. Use entry reference for log batch append
Bench results:
```
Patched:
test log_batch::tests::bench_log_batch_add_entry_and_encode ... bench:     136,299 ns/iter (+/- 44,912)
test log_batch::tests::bench_log_batch_add_entry_and_encode ... bench:     131,405 ns/iter (+/- 82,630)
Master:
test log_batch::tests::bench_log_batch_add_entry_and_encode ... bench:     199,314 ns/iter (+/- 95,954)
test log_batch::tests::bench_log_batch_add_entry_and_encode ... bench:     197,948 ns/iter (+/- 16,842)
Without streaming encoding(#91):
test log_batch::tests::bench_log_batch_add_entry_and_encode …
```
=> reduce allocation of log batch compression

src/file_pipe_log.rs, src/log_batch.rs, src/log_file.rs, src/pipe_log.rs, src/reader.rs
This PR contains some micro optimizations:
1. use `fdatasync` instead of `fsync`
2. Fallocate without `FALLOC_FL_KEEP_SIZE`
3. Reduce useless fallocate near end of file, so we don't need to truncate them again when rotating
Up to 60% throughput improvement:
```
> Commit 3a12e9b
- Thread 1
[write]
Throughput(QPS) = 8861.94
Latency(μs) min = 54, avg = 92.93, p50 = 89, p90 = 116, p95 = 127, p99 = 158, p99.9 = 379, max = 4979
Fairness = 100.0%
Write Bandwidth = 6.5MiB/s
- Thread 2
[write]
Throughput(QPS) = 18929.47
Latency(μs) min = 44, avg = 87.72, p50 = 84, p90 = 108, p95 = 120, p99 = 151, p99.9 = 393, max = 3977
Fairness = 100.0%
Write Bandwidth = 14.1MiB/s
- Thread 4
[write]
Throughput(QPS) = 33652.27
Latency(μs) min = 48, avg = 100.87, p50 = …
```
=> Add some micro optimizations

src/config.rs, src/file_pipe_log.rs, stress/src/main.rs
Previously, `fsync` is called outside of write mutex, which could results in excessive IOPS and hurts performance of other IO sensitive tasks resident on the same disk.
Add configuration item `parallelize_fsync` to toggle between fsync inside/outside write mutex.
Benchmark shows less than 3% regression for single thread workload:
```
Master:
- Thread 1
[write]
Throughput(QPS) = 13878.95
Latency(μs) min = 23, avg = 53.08, p50 = 41, p90 = 100, p95 = 122, p99 = 162, p99.9 = 258, max = 3991
Fairness = 100.0%
Write Bandwidth = 10.3MiB/s
Patched:
- Thread 1
[write]
Throughput(QPS) = 13562.47
Latency(μs) min = 23, avg = 54.68, p50 = 43, p90 = 103, p95 = 125, p99 = 164, p99.9 = 253, max = 2985
Fairness = 100.0%
Write Bandwidth = 10.1MiB/s
```
=> Support configuring parallelizing fsync

src/engine.rs, src/log_batch.rs
Protobuf message can be serialized to empty string (when its content is default zeros). But raft engine assumes otherwise, and yields error because it fails to locate checksum for empty strings.
=> fix bug when writing empty protobuf message

Cargo.toml
To fix https://github.com/tikv/tikv/issues/10997, we need to update `rust-prometheus` in TiKV to 0.13. As a dependency of TiKV, the `rust-prometheus` in `raft-engine` should be updated first.
This PR updates `rust-prometheus` to 0.13.
=> Update `rust-prometheus` to 0.13

src/engine.rs, src/file_builder.rs, src/file_pipe_log.rs, src/log_batch.rs, src/memtable.rs, src/purge.rs, src/reader.rs, src/test_util.rs
Overhaul unit tests for engine. Discover and fix several bugs:
- First rewrite entry could have larger index than first append entry, and causes panic
- Region tombstone in append queue is not applied to rewrite queue during recovery
- [NOT FIXED] State tombstone is lost during rewrite #141
- Rewrite queue log index could jump back, and causes panic
- [NOT FIXED] Recreated region is deleted after rewrite #142
=> overhaul engine tests and fix bugs

src/engine.rs, src/file_pipe_log.rs, src/log_file.rs, tests/failpoints/test_engine.rs, tests/failpoints/test_io_error.rs, tests/failpoints/util.rs
We should guarantee the in-memory states of objects are still consistent after exception (error or panic). i.e. We should be able to operate on `Engine` even after catching a panic from it. Reorder some the execution to achieve that, and add test cases for verification.
Some other considerations during overhaul:
- Avoid `unwrap`-ing inside a `catch_unwind` block
- Clean up `ConcurrentWriteContext`
=> improve exception safety of FilePipeLog and overhaul failpoint tests

README.md, ctl/src/main.rs, src/config.rs, src/consistency.rs, src/engine.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/file_pipe_log/reader.rs, src/log_batch.rs, src/pipe_log.rs
Factor out and export some interfaces for interacting with low level files:
- `build_file_writer`
- `build_file_reader`
- `LogItemReader`
=> factor out low level details for debugging purposes

src/engine.rs, src/memtable.rs, src/metrics.rs, src/purge.rs, tests/failpoints/test_engine.rs
~It's possible that certain raft groups are not compacted due to upper level issues. Those laggers will block the garbage collection progress indefinitely. After this patch, they will be rewritten regardless of the amount of their containing entries.~
Fix three bugs found during stability tests:
- Log entry hole between rewrite files crashed recovery
- Rewrite of a rewritten key could encounter a newer append and causes panic
- Rewrite log batch size exceeds i32::MAX and fails compression
=> fix bugs related to purge rewrite

src/engine.rs, src/memtable.rs, src/purge.rs
The splitting logic introduced in #160 could rewrite empty log batch. Fix it. And add test cases.
=> do not rewrite empty log batch

Cargo.toml, src/file_pipe_log/log_file.rs, stress/Cargo.toml, stress/src/main.rs, tests/benches/bench_recovery.rs
Signed-off-by: Chojan Shang <psiace@outlook.com>
=> Bump nix, rand, and more

src/lib.rs, src/memtable.rs
BTreeMap has better cache locality (and possibly fewer instructions involved) for single key put scenario. Micro benchmarks shows 6% improvement:
```
vanilla:
test memtable::tests::bench_memtable_single_put             ... bench:         101 ns/iter (+/- 39)
test memtable::tests::bench_memtable_single_put             ... bench:          99 ns/iter (+/- 31)
test memtable::tests::bench_memtable_triple_puts            ... bench:         317 ns/iter (+/- 15)
test memtable::tests::bench_memtable_triple_puts            ... bench:         317 ns/iter (+/- 19)
btreemap:
test memtable::tests::bench_memtable_single_put             ... bench:          93 ns/iter (+/- 9)
test memtable::tests::bench_memtable_single_put             ... bench:          94 ns/iter (+/- 13)
test …
```
=> Use BTreeMap for memtable put

ctl/Cargo.toml, src/engine.rs, src/env/obfuscated.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/pipe_builder.rs
Two cases:
- File header of the last log file is broken.
- Interrupted I/Os is falsely considered EOF.
Patched the mocking filesystem to cover these cases.
=> Fix two cases of false positive corruption

README.md, ctl/src/main.rs, src/engine.rs, src/filter.rs, src/log_batch.rs, tests/benches/bench_recovery.rs
Micro-benchmark of fetching 100 entries from page cache:
```
Without block cache:
test engine::tests::bench_engine_fetch_entries              ... bench:     215,308 ns/iter (+/- 20,738)
test engine::tests::bench_engine_fetch_entries              ... bench:     215,171 ns/iter (+/- 25,321)
With block cache:
test engine::tests::bench_engine_fetch_entries              ... bench:      57,549 ns/iter (+/- 5,163)
test engine::tests::bench_engine_fetch_entries              ... bench:      54,762 ns/iter (+/- 4,250)
```
=> Add a thread local block cache to improve read performance

src/engine.rs, src/env/default.rs, src/env/mod.rs, src/env/obfuscated.rs, src/file_pipe_log/pipe_builder.rs, tests/failpoints/test_io_error.rs, tests/failpoints/util.rs
Previously `truncate` a written part will not reseek the file cursor. This could leave holes in log files.
This case is now captured by failpoint tests. It wasn't covered before because all writes were done atomically, there's no chance to truncate a written part.
Also make the recovery process more robust. If the data is opened with the wrong file system, log files won't be mistakenly deleted.
=> reseek after truncating log file

src/engine.rs, src/errors.rs, src/file_pipe_log/log_file.rs, src/filter.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, tests/failpoints/mod.rs
Ref #205
Some enhancements:
- Do not store log index inside `EntryIndex`.
- Reduce entry offset and entry len from u64 to u32. It won't cause regression because the length is already limited by compression (i32::MAX).
Size for one `EntryIndex` is reduced from 64 bytes to 48 bytes (25%).
stress benchmarks shows 18.7% improvement (compared to results in #207, normalized with write bandwidth):
```
Memory: 7003MiB
[write]
Throughput(QPS) = 32322.92
Latency(μs) min = 8, avg = 16.10, p50 = 13, p90 = 26, p95 = 31, p99 = 45, p99.9 = 79, max = 4867
Fairness = 100.0%
Write Bandwidth = 24.2MiB/s
```
=> Reduce size of `EntryIndex`

Cargo.toml, README.md, src/engine.rs, src/memtable.rs, src/metrics.rs, stress/src/main.rs
Ref #205 
Added a new method to flush internal metrics, including memory used by `MemTables`.
=> trace memory of MemTables

src/log_batch.rs
Adding an empty list of entries to log batch should not change the output of `is_empty()`.
=> fix `LogBatch::is_empty()`

src/engine.rs, src/filter.rs, src/log_batch.rs, src/memtable.rs, src/test_util.rs, tests/failpoints/test_io_error.rs
Ref #205 
Previously, we store the (offset, length) of each entry in memory. In this PR, the length field is encoded in on-disk data to reduce memory usage.
The size of `ThinEntryIndex` is now 40B compared to 64B in v0.1.0.
=> offload in-memory `entry_len` field to disk

CHANGELOG.md, src/env/default.rs, src/errors.rs, src/file_pipe_log/log_file.rs, tests/failpoints/test_io_error.rs
`fallocate` is more performant but not supported on some platforms. This patch ignores its error.
Also fix the issue that `std::io::Error` doesn't print well for custom error kind.
=> tolerate fallocate failure and print IO error in debug form

CHANGELOG.md, src/env/default.rs, src/errors.rs, src/file_pipe_log/log_file.rs, tests/failpoints/test_io_error.rs
=> tolerate fallocate failure and print IO error in debug form (#225)

CHANGELOG.md, src/engine.rs, src/env/default.rs, src/env/mod.rs, src/env/obfuscated.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/lib.rs, tests/failpoints/test_engine.rs
User should be allowed to manage file deletion. For example, in TiKV, file encryption key can be deleted once the corresponding file is deleted.
=> Add metadata deletion capability to `FileSystem` trait

CHANGELOG.md, src/engine.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/pipe.rs, src/lib.rs, src/log_batch.rs, src/metrics.rs, src/purge.rs, src/write_barrier.rs, tests/failpoints/test_engine.rs
This PR tries to add RocksDB-like perf contexts to Raft Engine.
Now, I only add these statistics:
- `log_populating_nanos`
- `write_leader_wait_nanos`
- `log_write_nanos`
- `log_rotate_nanos`
- `log_sync_nanos`
- `write_apply_nanos`
I'm willing to know if there are other important metrics that is worth recording here.
=> Record perf contexts to the write procedure

src/engine.rs, src/env/mod.rs, src/file_pipe_log/pipe_builder.rs
There is no reason to return `exist` when we already have `exists_metadata` method.
=> simplify `delete_metadata` trait method

ctl/src/lib.rs
=> support running ctl command with custom file system

examples/append_compact_purge.rs
This commit is used to close #239.
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
```Rust
diff --git a/examples/append_compact_purge.rs b/examples/append_compact_purge.rs
index b9ebc1a..0565e44 100644
--- a/examples/append_compact_purge.rs
+++ b/examples/append_compact_purge.rs
@@ -51,11 +51,11 @@ fn main() {
loop {
for _ in 0..1024 {
let region = rand_regions.next().unwrap();
-            let state = engine
+            let mut state = engine
.get_message::<RaftLocalState>(region, b"last_index")
.unwrap()
.unwrap_or_else(|| init_state.clone());
-
+            state.last_index += 1; // manually update the state
let mut e = entry.clone();
e.index = state.last_index + 1;
batch.add_entries::<MessageExtTyped>(region, &[e]).unwrap();
```
With this patch, the logging of …
=> fix issue in append_compact_purge example

src/env/default.rs
EAGAIN error code Appears only when the O_NONBLOCK option is set and there is no more content in the file to read.
If a read() is interrupted by a signal before it reads any data, it shall return -1 with errno set to [EINTR].
=> refactor: catch errno EINTR when reading and writing files instead of EAGAIN

CHANGELOG.md, src/engine.rs, src/memtable.rs
Signed-off-by: 5kbpers <hustmh@gmail.com>
=> add `scan_messages` for iterating over messages

CHANGELOG.md, src/env/default.rs, src/file_pipe_log/log_file.rs, tests/failpoints/test_io_error.rs
=> pipe: reseek after write failure

src/memtable.rs, tests/failpoints/test_engine.rs
=> fix append recovery bug

Cargo.toml, src/config.rs, src/engine.rs, src/file_pipe_log/format.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/file_pipe_log/reader.rs, src/filter.rs, src/lib.rs, src/log_batch.rs, src/pipe_log.rs, src/util.rs, stress/src/main.rs, tests/failpoints/test_engine.rs
For closing #246, this pr is set. This pr is used for building basics for the new DIO feature, including:
* [New] DataLayout, representing the arrangement on data (records), in alignment or not.
* Refactor LogFileFormat / LogFileContext.
* Add extra support in `stress` tool for the new `alignment-mode` reading.
=> Support reading block based log format

CHANGELOG.md, src/engine.rs
Signed-off-by: 5kbpers <hustmh@gmail.com>
=> Add `Engine::get` for getting raw value

src/config.rs, src/engine.rs, src/file_pipe_log/pipe.rs
* Putting mutable operations into methods
* Clean up tests
* Log recycling doesn't affect `purge_to` return value any more
* Disallow reading stale files via pipe_log
* Enable recycling for tests
=> clean up file collection

CHANGELOG.md, src/config.rs, tests/failpoints/test_engine.rs
Default enable log recycling. Close #263.
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
=> Default enable log recycling

CHANGELOG.md, src/config.rs, src/engine.rs, src/env/default.rs, src/env/mod.rs, src/env/obfuscated.rs, src/file_pipe_log/log_file.rs, src/file_pipe_log/pipe.rs, src/log_batch.rs, src/memtable.rs, src/pipe_log.rs, src/purge.rs, tests/failpoints/test_engine.rs, tests/failpoints/test_io_error.rs
This is a preparing work for #258.
Changes:
- Move `fsync` to file handle instead of writer, so that we can call it concurrently in the future. In doing so, we have to remove the sync offset tracking and deprecate `bytes_per_sync` support
- Move `prepare_write` into pipe_log. Introduce a trait `ReactiveBytes` for this purpose.
- Rotate the file during write instead of doing it every write group, the timing is also delayed to the next write after exceeding limit (instead of the write that exceeds the limit).
- Differentiate two types of I/O errors: unrecoverable error from fsync, and retriable error from pwrite. Only bubble error for the latter case, panic early for unrecoverable ones.
- Also refactor the purge code, fix two cases where force-compact is not triggered
=> hide more file writing details from engine

CHANGELOG.md, src/engine.rs
Close #266
An empty batch went through `finish_populate` but not `drain` (in memtable apply block). This will break internal state machine and panic.
=> fix panic when reusing a was-empty batch

CHANGELOG.md, src/config.rs
Disable `enable-log-recycle` in raft-engine by default.
When opening `log recycling`,
> We observe on physical disk, overwriting existing log files will generate unnecessary read I/Os, and even though the fdatasync latency is reduced, the duration sum of fdatasync and pwrite has increased.
So, we disable it by default.
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
=> Disable `enable-log-recycle` by default.

src/config.rs, src/engine.rs
Sometimes the `purge_expired_files` is not called in time to release active log files. This leaves incoming writes unable to reuse stale logs anymore and causes performance jitters.
=> allow two more files for recycling

src/engine.rs
Related PR: https://github.com/tikv/tikv/pull/13633
Add an interface to  expose the path of raft engine to calculate raft engine capacity.
Signed-off-by: Jarvis Zheng <jiayang@hust.edu.cn>
=> Add interface to get the raft-engine path.

src/config.rs, src/file_pipe_log/pipe_builder.rs
This pr is used to unleash the limitation of `prefill-for-recycle`, used to adaptive to the requirement of large threshold.
Related issue: https://github.com/tikv/tikv/issues/14468.
=> Expose the setting of the maximum size of `prefill-for-recycle` to users

CHANGELOG.md, src/engine.rs, src/memtable.rs, src/purge.rs, tests/failpoints/test_engine.rs
Close #315
Record the start and end position of an atomic group in memtable.
=> fix data loss caused by atomic group being partially purged

CHANGELOG.md, Makefile, src/file_pipe_log/mod.rs, src/file_pipe_log/pipe_builder.rs, src/file_pipe_log/reader.rs, src/log_batch.rs, tests/failpoints/mod.rs, tests/failpoints/test_engine.rs
There're three blocks in a batch: header, entries and footer. During recovery, we only read and verify the header and footer to reduce I/O overhead. But it's possible that only entries block is corrupted while header and footer are not.
Only one type of this corruption can be tolerated: fsync hasn't properly synchronized the entries block before the shutdown. In this PR we detect it by verify entries block of the tail record. The added overhead should be negligible.
=> detect entries block corruption of tail record

.github/workflows/rust.yml, Cargo.toml, Makefile, src/codec.rs, src/memtable.rs, src/metrics.rs, src/purge.rs, src/swappy_allocator.rs
=> fix issues on latest nightly and improve feature tests

.github/workflows/rust.yml, Cargo.toml, Makefile, src/env/default.rs, src/env/log_fd.rs, src/env/log_fd/plain.rs, src/env/log_fd/unix.rs, src/env/mod.rs, src/file_pipe_log/pipe.rs, src/fork.rs, src/lib.rs, src/swappy_allocator.rs, tests/failpoints/test_engine.rs, tests/failpoints/test_io_error.rs
Let cargo build pass under windows system:
1. use windows os specific symlink API in `fork.rs`
2. use different `LogFd` implementations in each os. Guarded (or choosen) by feature flags
- for non-linux or non-unix system, use the plain `std::fs` APIs instead
- for linux and unix system, still use the `nix` raw bindings
=> build on windows system.

.github/workflows/rust.yml
Disable windows build due to https://github.com/tikv/grpc-rs/issues/620. This issue only occurs on latest windows image.
=> disable windows build

src/purge.rs
In a cloud environment, refraining from unscheduling sync operations when rewriting memtables might result in an accumulation of unsynced bytes in the buffer. This accumulation has the potential to impede the foreground write progress during sync.
This pull request introduces periodic sync operations when the amount of stashed unsynced bytes exceeds a predefined threshold. This optimization aims to address the issue and enhance performance.
=> rewrite: optimize the interval of `sync` when rewriting memtables.

.github/workflows/rust.yml, Cargo.toml
This PR is designed to enhance the current CI workflow.
The specific changes involve extracting the relative nightly tests that were previously run on the `ubuntu-latest` environment and deploying them onto a custom workflow, which might be failed because of the limitation of DiskSpace. 
This new workflow will be maintained by the TiKV team to ensure ongoing stability and reliability of our testing processes.
=> CI: update CI workflows.

.github/workflows/rust.yml, src/engine.rs
Manual cp #370 to tikv-6.5 branch.
=> [Cherry-pick] Fix `panics` on reading entries by stale index. (#370)

.github/workflows/rust.yml, src/codec.rs, src/env/default.rs, src/file_pipe_log/pipe.rs, src/file_pipe_log/pipe_builder.rs, src/log_batch.rs, src/memtable.rs, src/metrics.rs, src/test_util.rs, src/util.rs, src/write_barrier.rs, tests/failpoints/test_engine.rs
This is a cherry-pick of #379
We need to restart the Raft Engine within a test case to apply a configuration change. To do this, we must ensure the LOCK files are released upon drop, allowing the engine to be reopened within the same process.
Also update rustc version and fix clippy errors, since some dependencies require higher versions of Rust
=> Release dir locks on engine closing

src/engine.rs
PR [#370](https://github.com/tikv/raft-engine/pull/370) fixed a panic issue caused by concurrent updates to `Memtable` followed by reads on stale indexes. However, we observed that this fix introduced performance regressions under concurrent read/write workloads.
When `fetch_entries_to` retrieves a large batch of entries from disk, write operations are blocked until the read completes, delaying `Memtable` updates and degrading throughput.
This PR optimizes `fetch_entries_to` to reduce contention and improve performance under mixed workloads.
| Branch | Status |
| --- | --- |
| [Master](https://github.com/tikv/raft-engine/commit/392f5e66f8286dc1b6d7cf69f2bc20ed72d40123) | ![image](https://github.com/user-attachments/assets/72b2e5b3-56a2-4938-aebd-15a3090b9e15) |
| This PR | …
=> Optimize `fetch_entries_to` function to avoid stucking `write` too long.

src/engine.rs
This is a manual CP of #382 
PR [#370](https://github.com/tikv/raft-engine/pull/370) fixed a panic issue caused by concurrent updates to `Memtable` followed by reads on stale indexes. However, we observed that this fix introduced performance regressions under concurrent read/write workloads.
When `fetch_entries_to` retrieves a large batch of entries from disk, write operations are blocked until the read completes, delaying `Memtable` updates and degrading throughput.
This PR optimizes `fetch_entries_to` to reduce contention and improve performance under mixed workloads.
| Branch | Status |
| --- | --- |
| [Master](https://github.com/tikv/raft-engine/commit/392f5e66f8286dc1b6d7cf69f2bc20ed72d40123) | ![image](https://github.com/user-attachments/assets/72b2e5b3-56a2-4938-aebd-15a3090b9e15) …
=> [cp-8.5] Optimize `fetch_entries_to` function to avoid stucking `write` too long. (#382)
